INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Grand Hotel', 'Economy single room', 100.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Grand Hotel', 'Economy double room', 150.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Olympia', 'Suite', 200.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Grand Hotel', 'Twin Room', 120.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Hotel Victoria', 'Family Room', 150.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Olympia', 'Economy single room', 110.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Olympia', 'Presidential suite', 320.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Grand Hotel', 'Suite', 220.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Grand Hotel', 'Family Room', 190.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Olympia', 'Twin Room', 130.00);
INSERT INTO m_burym.hotel_room (hotel_name, type_room, day_price) VALUES ('Hotel Victoria', 'Economy single room', 80.00);
